import { useWorkerClaims } from "@/hooks/use-claims";
import { useAuth } from "@/hooks/use-auth";
import { Card, CardContent, CardHeader, CardTitle, Badge } from "@/components/ui";
import { formatCurrency } from "@/lib/utils";
import { format } from "date-fns";
import { CloudLightning, Info } from "lucide-react";

export function WorkerClaims() {
  const { user } = useAuth();
  const { data, isLoading } = useWorkerClaims({ workerId: user?.id });

  if (isLoading) return <div className="p-8 flex justify-center"><div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full" /></div>;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-display font-bold mb-2">My Claims History</h1>
        <p className="text-muted-foreground">Automatic payouts generated by triggers in your active zone.</p>
      </div>

      <div className="bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200 p-4 rounded-xl flex gap-3 text-sm border border-blue-100 dark:border-blue-900/50">
        <Info className="h-5 w-5 shrink-0" />
        <p>GigShield claims are generated automatically when bad weather or outages occur. You do not need to file manual claims. Funds for approved claims are sent directly to your registered bank account within 24 hours.</p>
      </div>

      {data?.claims.length === 0 ? (
        <Card className="text-center py-16 bg-muted/20 border-dashed">
          <CardContent>
            <CloudLightning className="h-12 w-12 text-muted-foreground/30 mx-auto mb-4" />
            <h3 className="text-xl font-bold mb-2">No Claims Yet</h3>
            <p className="text-muted-foreground max-w-sm mx-auto">No disruption triggers have been recorded in your zone during your active policy periods.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {data?.claims.map((claim) => (
            <Card key={claim.id} className="card-hover">
              <CardContent className="p-6">
                <div className="flex flex-col md:flex-row justify-between md:items-center gap-4">
                  <div className="flex gap-4">
                    <div className="h-12 w-12 rounded-xl bg-secondary flex items-center justify-center shrink-0">
                      <CloudLightning className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                      <div className="flex items-center gap-3 mb-1">
                        <h3 className="font-bold text-lg capitalize">{claim.triggerType.replace('_', ' ')}</h3>
                        <Badge variant={
                          claim.status === 'paid' ? 'success' : 
                          claim.status === 'rejected' ? 'destructive' : 
                          claim.status === 'approved' ? 'default' : 'warning'
                        }>
                          {claim.status.toUpperCase()}
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground">{claim.triggerDescription}</p>
                      <div className="text-xs font-medium text-muted-foreground mt-2">
                        {format(new Date(claim.createdAt), "MMM do, yyyy 'at' h:mm a")} • Zone: {claim.zone}
                      </div>
                    </div>
                  </div>
                  
                  <div className="md:text-right pt-4 md:pt-0 border-t md:border-t-0 md:border-l md:pl-6">
                    <p className="text-sm font-medium text-muted-foreground mb-1">Payout Amount</p>
                    <p className="text-3xl font-bold text-foreground">{formatCurrency(claim.amount)}</p>
                    {claim.paidAt && (
                      <p className="text-xs text-success font-medium mt-1 flex items-center justify-end gap-1">
                        Paid on {format(new Date(claim.paidAt), "MMM do")}
                      </p>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
